const configuredUrl = process.env.NEXT_PUBLIC_SITE_URL

if (!configuredUrl && process.env.NODE_ENV === 'production') {
  // Every canonical, sitemap and JSON-LD URL is built from this. Silently
  // falling back would ship the whole site pointing at the wrong domain.
  throw new Error('Missing environment variable: NEXT_PUBLIC_SITE_URL')
}

// A trailing slash in the env var would turn every `${SITE_URL}/path` into `//path`.
export const SITE_URL = (configuredUrl ?? 'http://localhost:3000').replace(/\/+$/, '')

/**
 * Generated by app/opengraph-image.tsx. Defining `openGraph` in a page's
 * metadata replaces the file-convention image rather than merging with it, so
 * pages with no image of their own have to name this one explicitly.
 */
export const DEFAULT_OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
}

/** Trim to a length search engines and social cards actually display. */
export function metaDescription(text: string | undefined, max = 155): string | undefined {
  if (!text) return undefined
  const flat = text.replace(/\s+/g, ' ').trim()
  if (flat.length <= max) return flat
  const cut = flat.slice(0, max)
  const lastSpace = cut.lastIndexOf(' ')
  return `${(lastSpace > 60 ? cut.slice(0, lastSpace) : cut).replace(/[.,;:—-]$/, '')}…`
}
