import { defineType, defineField, defineArrayMember } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  fields: [
    defineField({
      name: 'ownerName',
      title: 'Owner / Business Name',
      type: 'string',
      description: 'Your full name — used throughout the site wherever your name appears.',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'logoText',
      title: 'Navbar Logo Text',
      type: 'string',
      description: 'Text shown in the top-left of the navigation bar. e.g. "CrossStrat" or your name.',
    }),
    defineField({
      name: 'ownerTitle',
      title: 'Your Title / Role',
      type: 'string',
      description: 'Your role shown on the site. e.g. "Retail Placement Consultant"',
    }),
    defineField({
      name: 'calendarUrl',
      title: 'Booking / Calendar Link',
      type: 'string',
      description: 'The URL visitors go to when they click "Book a Call". e.g. your Calendly link.',
    }),
    defineField({
      name: 'navHomeLabel',
      title: 'Navbar — Home Button',
      type: 'string',
      description: 'Text of the top-bar button that goes to the top of the home page. Also used in the footer. Leave blank to use "Home".',
    }),
    defineField({
      name: 'navBenefitsLabel',
      title: 'Navbar — Benefits Button',
      type: 'string',
      description: 'Text of the top-bar button that goes to the Benefits section of the home page. Also used in the footer. Leave blank to use "Why Partner With Us?".',
    }),
    defineField({
      name: 'navHowItWorksLabel',
      title: 'Navbar — How It Works Button',
      type: 'string',
      description: 'Text of the top-bar button that goes to the How It Works section of the home page. Also used in the footer. Leave blank to use "Getting Started".',
    }),
    defineField({
      name: 'navAboutLabel',
      title: 'Navbar — About Button',
      type: 'string',
      description: 'Text of the top-bar button that goes to the About page. Leave blank to use "About".',
    }),
    defineField({
      name: 'navContentLabel',
      title: 'Navbar — Content Button',
      type: 'string',
      description: 'Text of the top-bar button that goes to the Content (blog) page. Leave blank to use "Content".',
    }),
    defineField({
      name: 'navBookCallLabel',
      title: 'Navbar — Book a Call Button',
      type: 'string',
      description: 'Text of the top-bar button that goes to your booking link. Also used in the footer. Leave blank to use "Book a Call".',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact Email',
      type: 'string',
      description: 'Email address used on the contact form and in the footer.',
    }),
    defineField({
      name: 'footerTagline',
      title: 'Footer Tagline',
      type: 'text',
      rows: 2,
      description: 'Short tagline shown at the bottom of every page.',
    }),
    defineField({
      name: 'blogEyebrow',
      title: 'Blog Page — Small Label',
      type: 'string',
      description: 'Tiny label above the heading on the Content page. e.g. "Retail Insights"',
    }),
    defineField({
      name: 'blogHeadline',
      title: 'Blog Page — Heading (red part)',
      type: 'string',
      description: 'First half of the Content page heading, shown in red. e.g. "The"',
    }),
    defineField({
      name: 'blogHeadlineAccent',
      title: 'Blog Page — Heading (white part)',
      type: 'string',
      description: 'Second half of the Content page heading, shown in white. e.g. "Content"',
    }),
    defineField({
      name: 'blogSubheadline',
      title: 'Blog Page — Supporting Text',
      type: 'text',
      rows: 3,
      description: 'Paragraph below the Content page heading.',
    }),
    defineField({
      name: 'blogSeoDescription',
      title: 'Blog Page — Meta Description',
      type: 'text',
      rows: 2,
      description: 'Shown in Google results for the Content page (120–160 chars recommended).',
      validation: (r) => r.max(160).warning('Keep under 160 characters'),
    }),
    defineField({
      name: 'articleCtaHeadline',
      title: 'Article Footer CTA — Heading',
      type: 'string',
      description: 'Heading of the booking prompt at the bottom of every article. e.g. "Ready to get on shelves?"',
    }),
    defineField({
      name: 'articleCtaBody',
      title: 'Article Footer CTA — Supporting Text',
      type: 'text',
      rows: 3,
      description: 'Paragraph under that heading.',
    }),
    defineField({
      name: 'articleCtaButton',
      title: 'Article Footer CTA — Button Text',
      type: 'string',
      description: 'e.g. "Book a Strategy Call"',
    }),
    defineField({
      name: 'mosaicEyebrow',
      title: 'Media Section — Small Label',
      type: 'string',
      description: 'Tiny label above the media gallery heading on the blog page. e.g. "Behind The Scenes"',
    }),
    defineField({
      name: 'mosaicHeadline',
      title: 'Media Section — Heading',
      type: 'string',
      description: 'Main heading over the media gallery. e.g. "See it in"',
    }),
    defineField({
      name: 'mosaicHeadlineAccent',
      title: 'Media Section — Heading Italic Part',
      type: 'string',
      description: 'The words in the heading that appear in italic. e.g. "action"',
    }),
    defineField({
      name: 'socialLinks',
      title: 'Social Links',
      type: 'array',
      description: 'Links to your social/professional profiles (e.g. LinkedIn). Used in site structured data.',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({
              name: 'platform',
              title: 'Platform',
              type: 'string',
              description: 'e.g. "LinkedIn", "Instagram"',
            }),
            defineField({
              name: 'url',
              title: 'URL',
              type: 'url',
              validation: (r) => r.required(),
            }),
          ],
          preview: { select: { title: 'platform', subtitle: 'url' } },
        }),
      ],
    }),
  ],
})
